// File generated by proxmox json schema, DO NOT EDIT

package mgr

import (
	"context"
)

type HTTPClient interface {
	Do(context.Context, string, string, interface{}, interface{}) error
}

type Client struct {
	httpClient HTTPClient
}

func New(c HTTPClient) *Client {
	return &Client{
		httpClient: c,
	}
}

type IndexRequest struct {
	Node string `url:"node",json:"node"`
}

type IndexResponse []*struct {
	Addr  *string `url:"addr,omitempty",json:"addr,omitempty"`
	Host  *string `url:"host,omitempty",json:"host,omitempty"`
	State string  `url:"state",json:"state"`
}

// Index MGR directory index.
func (c *Client) Index(ctx context.Context, req *IndexRequest) (*IndexResponse, error) {
	var resp *IndexResponse

	err := c.httpClient.Do(ctx, "/nodes/{node}/ceph/mgr", "GET", &resp, req)
	return resp, err
}

type ChildCreateRequest struct {
	Id   *string `url:"id,omitempty",json:"id,omitempty"`
	Node string  `url:"node",json:"node"`
}

type ChildCreateResponse string

// ChildCreate Create Ceph Manager
func (c *Client) ChildCreate(ctx context.Context, req *ChildCreateRequest) (*ChildCreateResponse, error) {
	var resp *ChildCreateResponse

	err := c.httpClient.Do(ctx, "/nodes/{node}/ceph/mgr/{id}", "POST", &resp, req)
	return resp, err
}

type DeleteRequest struct {
	Id   string `url:"id",json:"id"`
	Node string `url:"node",json:"node"`
}

type DeleteResponse string

// Delete Destroy Ceph Manager.
func (c *Client) Delete(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	var resp *DeleteResponse

	err := c.httpClient.Do(ctx, "/nodes/{node}/ceph/mgr/{id}", "DELETE", &resp, req)
	return resp, err
}
