// File generated by proxmox json schema, DO NOT EDIT

package aliases

import (
	"context"
)

type HTTPClient interface {
	Do(context.Context, string, string, interface{}, interface{}) error
}

type Client struct {
	httpClient HTTPClient
}

func New(c HTTPClient) *Client {
	return &Client{
		httpClient: c,
	}
}

type IndexResponse []*struct {
	Cidr    string  `url:"cidr",json:"cidr"`
	Comment *string `url:"comment,omitempty",json:"comment,omitempty"`
	Digest  string  `url:"digest",json:"digest"`
	Name    string  `url:"name",json:"name"`
}

// Index List aliases
func (c *Client) Index(ctx context.Context) (*IndexResponse, error) {
	var resp *IndexResponse

	err := c.httpClient.Do(ctx, "/cluster/firewall/aliases", "GET", &resp, nil)
	return resp, err
}

type CreateRequest struct {
	Cidr    string  `url:"cidr",json:"cidr"`
	Comment *string `url:"comment,omitempty",json:"comment,omitempty"`
	Name    string  `url:"name",json:"name"`
}

type CreateResponse map[string]interface{}

// Create Create IP or Network Alias.
func (c *Client) Create(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	var resp *CreateResponse

	err := c.httpClient.Do(ctx, "/cluster/firewall/aliases", "POST", &resp, req)
	return resp, err
}

type FindRequest struct {
	Name string `url:"name",json:"name"`
}

type FindResponse map[string]interface{}

// Find Read alias.
func (c *Client) Find(ctx context.Context, req *FindRequest) (*FindResponse, error) {
	var resp *FindResponse

	err := c.httpClient.Do(ctx, "/cluster/firewall/aliases/{name}", "GET", &resp, req)
	return resp, err
}

type UpdateRequest struct {
	Rename  *string `url:"rename,omitempty",json:"rename,omitempty"`
	Cidr    string  `url:"cidr",json:"cidr"`
	Comment *string `url:"comment,omitempty",json:"comment,omitempty"`
	Digest  *string `url:"digest,omitempty",json:"digest,omitempty"`
	Name    string  `url:"name",json:"name"`
}

type UpdateResponse map[string]interface{}

// Update Update IP or Network alias.
func (c *Client) Update(ctx context.Context, req *UpdateRequest) (*UpdateResponse, error) {
	var resp *UpdateResponse

	err := c.httpClient.Do(ctx, "/cluster/firewall/aliases/{name}", "PUT", &resp, req)
	return resp, err
}

type DeleteRequest struct {
	Digest *string `url:"digest,omitempty",json:"digest,omitempty"`
	Name   string  `url:"name",json:"name"`
}

type DeleteResponse map[string]interface{}

// Delete Remove IP or Network alias.
func (c *Client) Delete(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	var resp *DeleteResponse

	err := c.httpClient.Do(ctx, "/cluster/firewall/aliases/{name}", "DELETE", &resp, req)
	return resp, err
}
