// File generated by proxmox json schema, DO NOT EDIT

package lvmthin

import (
	"context"
)

type HTTPClient interface {
	Do(context.Context, string, string, interface{}, interface{}) error
}

type Client struct {
	httpClient HTTPClient
}

func New(c HTTPClient) *Client {
	return &Client{
		httpClient: c,
	}
}

type IndexRequest struct {
	Node string `url:"node",json:"node"`
}

type IndexResponse []*struct {
	Vg           string `url:"vg",json:"vg"`
	Lv           string `url:"lv",json:"lv"`
	LvSize       int    `url:"lv_size",json:"lv_size"`
	MetadataSize int    `url:"metadata_size",json:"metadata_size"`
	MetadataUsed int    `url:"metadata_used",json:"metadata_used"`
	Used         int    `url:"used",json:"used"`
}

// Index List LVM thinpools
func (c *Client) Index(ctx context.Context, req *IndexRequest) (*IndexResponse, error) {
	var resp *IndexResponse

	err := c.httpClient.Do(ctx, "/nodes/{node}/disks/lvmthin", "GET", &resp, req)
	return resp, err
}

type CreateRequest struct {
	AddStorage *bool  `url:"add_storage,omitempty",json:"add_storage,omitempty"`
	Device     string `url:"device",json:"device"`
	Name       string `url:"name",json:"name"`
	Node       string `url:"node",json:"node"`
}

type CreateResponse string

// Create Create an LVM thinpool
func (c *Client) Create(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	var resp *CreateResponse

	err := c.httpClient.Do(ctx, "/nodes/{node}/disks/lvmthin", "POST", &resp, req)
	return resp, err
}

type DeleteRequest struct {
	CleanupConfig *bool  `url:"cleanup-config,omitempty",json:"cleanup-config,omitempty"`
	CleanupDisks  *bool  `url:"cleanup-disks,omitempty",json:"cleanup-disks,omitempty"`
	Name          string `url:"name",json:"name"`
	Node          string `url:"node",json:"node"`
	VolumeGroup   string `url:"volume-group",json:"volume-group"`
}

type DeleteResponse string

// Delete Remove an LVM thin pool.
func (c *Client) Delete(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	var resp *DeleteResponse

	err := c.httpClient.Do(ctx, "/nodes/{node}/disks/lvmthin/{name}", "DELETE", &resp, req)
	return resp, err
}
